apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      component: authentication
  template:
    metadata:
      labels:
        component: authentication
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/plenary-truck-252305/authenticationservice:1.0.3
        name: authentication
        ports:
        - containerPort: 80