apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      component: campaign
  template:
    metadata:
      labels:
        component: campaign
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/plenary-truck-252305/campaignservice:1.0.2
        name: campaign
        ports:
        - containerPort: 80